apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fix-pv.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "fix-pv.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
    spec:
      serviceAccountName: {{ include "fix-pv.serviceAccountName" . }}
      containers:
        - name: fixer
          image: "ghcr.io/svix-jbrown/clickhouse-fix-pvs:latest"
          imagePullPolicy: "IfNotPresent"
      restartPolicy: OnFailure
