on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      meta-images: svix-jbrown/clickhouse-fix-pvs
      cache: true
      cache-scope: build
      cache-mode: max
      meta-flavor: |
        latest=true
      meta-tags: |
        type=ref,event=branch
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
